//This is supposed to be source code
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
//Making it bigger to test if new DLL version can be published to MyGet with same NuGet package version
